### ISSUE TITLE
Modification on code not in the OS image

### ISSUE THREAD

**Issue by cibersheep** [ubports/settings-components#12]
After some MRs, qml changes are not reflected in the OS image.
I.e.:
- https://github.com/ubports/settings-components/pull/5 should change the colors of Dialog buttons to the current theme and HIG but Dialog still shows old color scheme:

![imatge](https://user-images.githubusercontent.com/6640041/80150006-e2467880-85b7-11ea-9d1f-5968c1b851d2.png)

- The recent https://github.com/ubports/settings-components/pull/8 should change the view of the ListView but as Bolly [shows](recent https://github.com/ubports/settings-components/pull/8#issuecomment-618543909 ), old behaviour is still in the yesterday update

Is something I need to do?

**Comment by Flohack74** [comment]
Does this only affect this component or other changes to UI as well?

**Comment by Flohack74** [comment]
Oh all stuff was made against master branch, but we need it in xenial branch. I try to fix that... xenial is now the default branch, should not happen again ;)

**Comment by cibersheep** [comment]
Oh, I see. Tell me if you need me to push to xenial instead

**Comment by Flohack74** [comment]
Can you check again, should be in now ;)

**Comment by cibersheep** [comment]
~~I'll do soon~~
YES! Lovely, thank you <3
